# Generated by Django 3.2.8 on 2021-10-30 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=130)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('choices', models.CharField(choices=[('both', 'Both'), ('notary', 'Notary'), ('bookkeeping', 'Bookkeeping')], max_length=100, null=True)),
                ('phone', models.CharField(max_length=15)),
            ],
        ),
    ]
