# Generated by Django 3.2.8 on 2021-10-30 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_customer_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='detail',
            field=models.CharField(default='Add Details', max_length=100),
        ),
    ]
